from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
import sys



class Ui_App(object):
    def setupUi(self, App):
        App.setObjectName("App")     
        App.resize(1184, 722)
        
        self.Controller = QtWidgets.QGroupBox(App)
        self.Controller.setGeometry(QtCore.QRect(190, 10, 991, 171))
        self.Controller.setObjectName("Controller")
        self.Serial = QtWidgets.QGroupBox(self.Controller)
        self.Serial.setGeometry(QtCore.QRect(0, 20, 781, 71))
        self.Serial.setObjectName("Serial")
        self.Baudrates = QtWidgets.QComboBox(self.Serial)
        self.Baudrates.setGeometry(QtCore.QRect(81, 25, 75, 35))
        self.Baudrates.setObjectName("Baudrates")
        self.Baudrates.addItem("")
        self.Baudrates.setItemText(0, "")
        self.Baudrates.addItem("")
        self.Baudrates.addItem("")
        self.Baudrates.addItem("")
        self.Baudrates.addItem("")
        self.Baudrates.addItem("")
        self.Baudrates.addItem("")
        self.Baudrates.addItem("")
        self.Baudrates.addItem("")
        self.Baudrates.addItem("")
        self.Baudrates.addItem("")
        self.Baudrates.addItem("")
        self.label = QtWidgets.QLabel(self.Serial)
        self.label.setGeometry(QtCore.QRect(10, 30, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Serial)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Com = QtWidgets.QComboBox(self.Serial)
        self.Com.setGeometry(QtCore.QRect(203, 25, 75, 35))
        self.Com.setObjectName("Com")
        self.Com.addItem("")
        self.Com.setItemText(0, "")
        self.Com.addItem("")
        self.Com.addItem("")
        self.Com.addItem("")
        self.Com.addItem("")
        self.Com.addItem("")
        self.Com.addItem("")
        self.Com.addItem("")
        self.Com.addItem("")
        self.Com.addItem("")
        self.Com.addItem("")
        self.Com.addItem("")
        self.Com.addItem("")
        self.label_3 = QtWidgets.QLabel(self.Serial)
        self.label_3.setGeometry(QtCore.QRect(290, 30, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Serial)
        self.label_4.setGeometry(QtCore.QRect(445, 30, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.DataSize = QtWidgets.QComboBox(self.Serial)
        self.DataSize.setGeometry(QtCore.QRect(367, 25, 75, 35))
        self.DataSize.setObjectName("DataSize")
        self.DataSize.addItem("")
        self.DataSize.setItemText(0, "")
        self.DataSize.addItem("")
        self.DataSize.addItem("")
        self.Parity = QtWidgets.QComboBox(self.Serial)
        self.Parity.setGeometry(QtCore.QRect(493, 25, 75, 35))
        self.Parity.setObjectName("Parity")
        self.Parity.addItem("")
        self.Parity.addItem("")
        self.Parity.addItem("")
        self.Parity.addItem("")
        self.Connect = QtWidgets.QPushButton(self.Serial)
        self.Connect.setGeometry(QtCore.QRect(680, 25, 75, 35))
        self.Connect.setObjectName("Connect")
        
        self.Saver = QtWidgets.QGroupBox(self.Controller)
        self.Saver.setGeometry(QtCore.QRect(0, 90, 991, 81))
        self.Saver.setObjectName("Saver")
        self.Record = QtWidgets.QPushButton(self.Saver)
        self.Record.setGeometry(QtCore.QRect(900, 30, 75, 35))
        self.Record.setObjectName("Record")
        self.label_5 = QtWidgets.QLabel(self.Saver)
        self.label_5.setGeometry(QtCore.QRect(140, 40, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Type = QtWidgets.QComboBox(self.Saver)
        self.Type.setGeometry(QtCore.QRect(182, 35, 75, 31))
        self.Type.setObjectName("Type")
        self.Type.addItem("")
        self.Type.setItemText(0, "")
        self.Type.addItem("")
        self.Type.addItem("")
        self.label_6 = QtWidgets.QLabel(self.Saver)
        self.label_6.setGeometry(QtCore.QRect(265, 40, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Name = QtWidgets.QTextEdit(self.Saver)
        self.Name.setGeometry(QtCore.QRect(315, 35, 75, 31))
        self.Name.setObjectName("Name")
        self.label_7 = QtWidgets.QLabel(self.Saver)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.Model = QtWidgets.QComboBox(self.Saver)
        self.Model.setGeometry(QtCore.QRect(60, 35, 75, 31))
        self.Model.setObjectName("Model")
        self.Model.addItem("")
        self.Model.setItemText(0, "")
        self.Model.addItem("")
        # self.label_10 = QtWidgets.QLabel(self.Saver)
        # self.label_10.setGeometry(QtCore.QRect(395,40,70,16))
        # self.label_10.setFont(font)
        # self.label_10.setObjectName("label_10")
        # self.Labeler = QtWidgets.QTextEdit(self.Saver)
        # self.Labeler.setGeometry(QtCore.QRect(463, 35, 75, 31))
        # self.Labeler.setObjectName("Labeler")
       

        self.Stream = QtWidgets.QGroupBox(self.Controller)
        self.Stream.setGeometry(QtCore.QRect(790, 20, 191, 71))
        self.Stream.setObjectName("Stream")
        self.Start = QtWidgets.QPushButton(self.Stream)
        self.Start.setGeometry(QtCore.QRect(10, 30, 80, 25))
        self.Start.setObjectName("Start")
        self.Reset = QtWidgets.QPushButton(self.Stream)
        self.Reset.setGeometry(QtCore.QRect(100, 30, 80, 25))
        self.Reset.setObjectName("Reset")
       
        self.SeriaPlotter = QtWidgets.QGroupBox(App)
        self.SeriaPlotter.setGeometry(QtCore.QRect(550, 190, 631, 521))
        self.SeriaPlotter.setObjectName("SeriaPlotter")
        self.Plotter = PlotWidget(self.SeriaPlotter)
        self.Plotter.setGeometry(QtCore.QRect(0, 20, 631, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Plotter.sizePolicy().hasHeightForWidth())
        self.Plotter.setSizePolicy(sizePolicy)
        self.Plotter.setObjectName("Plotter")
        self.SerialMonitor = QtWidgets.QGroupBox(App)
        
        self.SerialMonitor.setGeometry(QtCore.QRect(10, 190, 521, 201))
        self.SerialMonitor.setObjectName("SerialMonitor")
        self.Monitor = QtWidgets.QTextBrowser(self.SerialMonitor)
        self.Monitor.setGeometry(QtCore.QRect(0, 20, 521, 141))
        self.Monitor.setObjectName("Monitor")
        self.AutoScroll = QtWidgets.QCheckBox(self.SerialMonitor)
        self.AutoScroll.setGeometry(QtCore.QRect(410, 170, 91, 22))
        self.AutoScroll.setObjectName("AutoScroll")
        self.label_8 = QtWidgets.QLabel(self.SerialMonitor)
        self.label_8.setGeometry(QtCore.QRect(10, 170, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.SerialMonitor)
        self.label_9.setGeometry(QtCore.QRect(170, 170, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Max = QtWidgets.QTextBrowser(self.SerialMonitor)
        self.Max.setGeometry(QtCore.QRect(50, 170, 101, 21))
        self.Max.setObjectName("Max")
        self.Min = QtWidgets.QTextBrowser(self.SerialMonitor)
        self.Min.setGeometry(QtCore.QRect(210, 170, 101, 21))
        self.Min.setObjectName("Min")
        
        self.Send = QtWidgets.QGroupBox(App)
        self.Send.setGeometry(QtCore.QRect(10, 390, 521, 71))
        self.Send.setObjectName("Send")
        self.textEdit_2 = QtWidgets.QTextEdit(self.Send)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 30, 311, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.Hex = QtWidgets.QCheckBox(self.Send)
        self.Hex.setGeometry(QtCore.QRect(330, 30, 83, 22))
        self.Hex.setObjectName("Hex")
        self.Send_2 = QtWidgets.QPushButton(self.Send)
        self.Send_2.setGeometry(QtCore.QRect(420, 30, 80, 25))
        self.Send_2.setObjectName("Send_2")
       
        self.Logo = QtWidgets.QLabel(App)
        self.Logo.setGeometry(QtCore.QRect(10, 20, 171, 161))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("D:\Workspace\Vulcan\App\AppPy\logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setObjectName("Logo")
        self.retranslateUi(App)

        self.timer_getdata = QtCore.QTimer()
        self.timer_getdata.setInterval(105)


        QtCore.QMetaObject.connectSlotsByName(App)

    def retranslateUi(self, App):
        _translate = QtCore.QCoreApplication.translate
        App.setWindowTitle(_translate("App", "Vulcan Augmetics"))
        # App.mapToGlobal
        self.Controller.setTitle(_translate("App", "Controller"))
        self.Serial.setTitle(_translate("App", "Serial"))
        self.Baudrates.setItemText(1, _translate("App", "600"))
        self.Baudrates.setItemText(2, _translate("App", "1200"))
        self.Baudrates.setItemText(3, _translate("App", "2400"))
        self.Baudrates.setItemText(4, _translate("App", "4800"))
        self.Baudrates.setItemText(5, _translate("App", "9600"))
        self.Baudrates.setItemText(6, _translate("App", "14400"))
        self.Baudrates.setItemText(7, _translate("App", "19200"))
        self.Baudrates.setItemText(8, _translate("App", "38400"))
        self.Baudrates.setItemText(9, _translate("App", "56000"))
        self.Baudrates.setItemText(10, _translate("App", "57600"))
        self.Baudrates.setItemText(11, _translate("App", "115200"))
        self.label.setText(_translate("App", "Baudrate:"))
        self.label_2.setText(_translate("App", "COM:"))
        self.Com.setItemText(1, _translate("App", "COM1"))
        self.Com.setItemText(2, _translate("App", "COM2"))
        self.Com.setItemText(3, _translate("App", "COM3"))
        self.Com.setItemText(4, _translate("App", "COM4"))
        self.Com.setItemText(5, _translate("App", "COM5"))
        self.Com.setItemText(6, _translate("App", "COM6"))
        self.Com.setItemText(7, _translate("App", "COM7"))
        self.Com.setItemText(8, _translate("App", "COM8"))
        self.Com.setItemText(9, _translate("App", "COM9"))
        self.Com.setItemText(10, _translate("App", "COM10"))
        self.Com.setItemText(11, _translate("App", "COM11"))
        self.Com.setItemText(12, _translate("App", "COM12"))
        self.label_3.setText(_translate("App", "Data Size:"))
        self.label_4.setText(_translate("App", "Parity:"))
        self.DataSize.setItemText(1, _translate("App", "7"))
        self.DataSize.setItemText(2, _translate("App", "8"))
        self.Parity.setItemText(0, _translate("App", "none"))
        self.Parity.setItemText(1, _translate("App", "odd"))
        self.Parity.setItemText(2, _translate("App", "even"))
        self.Parity.setItemText(3, _translate("App", "mark"))
        self.Connect.setText(_translate("App", "Connect"))
        self.Saver.setTitle(_translate("App", "Saver"))
        self.Record.setText(_translate("App", "Record"))
        self.label_5.setText(_translate("App", "Type:"))
        self.Type.setItemText(1, _translate("App", "csv"))
        self.Type.setItemText(2, _translate("App", "xlsx"))
        self.label_6.setText(_translate("App", "Name:"))
        self.label_7.setText(_translate("App", "Model:"))
        self.Model.setItemText(1, _translate("App", "Mark9.7"))
        self.Stream.setTitle(_translate("App", "Stream"))
        self.Start.setText(_translate("App", "Start"))
        self.Reset.setText(_translate("App", "Reset"))
        self.SeriaPlotter.setTitle(_translate("App", "Serial Plotter"))
        self.SerialMonitor.setTitle(_translate("App", "Serrial Monitor"))
        self.AutoScroll.setText(_translate("App", "Auto Scroll"))
        self.label_8.setText(_translate("App", "Max:"))
        self.label_9.setText(_translate("App", "Min:"))
        self.Send.setTitle(_translate("App", "Send"))
        self.Hex.setText(_translate("App", "Hex"))
        self.Send_2.setText(_translate("App", "Send"))

        # self.label_10.setText(_translate("App", "Label Data:"))